---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--context=dir://kaniko-demo",
           "--dockerfile=/kaniko-demo/Dockerfile",
            "--destination=brajputbrinda/devops-toolkit:1.0.1"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: my-volume
        mountPath: /data
    command: ["/bin/sh"]
    args: ["-c", "git clone https://github.com/myusername/myrepo.git /source && cp -R /source/. /data/"]

  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc

